import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "How Vaktram collects, uses, and protects your data.",
};

export default function PrivacyPage() {
  return (
    <main className="bg-white py-20">
      <article className="container-tight prose prose-slate max-w-3xl">
        <p className="eyebrow">Legal</p>
        <h1 className="display mt-4 text-4xl sm:text-5xl">Privacy Policy</h1>
        <p className="mt-3 text-sm text-slate-500">Last updated: 2026-05-04</p>

        <Section title="1. Who we are">
          Vaktram is a meeting-notes platform operated by Vaktram Technologies.
          We can be reached at{" "}
          <a className="text-slate-900 underline" href="mailto:hello@vaktram.com">
            hello@vaktram.com
          </a>
          .
        </Section>

        <Section title="2. What we collect">
          <ul>
            <li>
              <b>Account data.</b> Name, email, organisation name, hashed
              password, and any phone number you choose to provide.
            </li>
            <li>
              <b>Meeting data.</b> Audio recordings, transcripts, and the
              summaries generated by your chosen LLM provider. Stored in the
              region you pin (Singapore, EU, or US).
            </li>
            <li>
              <b>Configuration.</b> Encrypted LLM API keys (Fernet),
              calendar tokens, retention policies, and audit logs.
            </li>
            <li>
              <b>Operational telemetry.</b> Request logs, error traces, and
              performance metrics. We do not log meeting content.
            </li>
          </ul>
        </Section>

        <Section title="3. What we do not collect">
          <ul>
            <li>
              We do not record meetings without your explicit dispatch.
            </li>
            <li>
              We do not call your LLM provider on your behalf except to
              fulfil your specific request.
            </li>
            <li>
              We do not sell your data, transcripts, or any usage data.
            </li>
          </ul>
        </Section>

        <Section title="4. How we use your data">
          <ul>
            <li>To run the recording, transcription, and summary pipeline.</li>
            <li>To authenticate you and prevent abuse.</li>
            <li>
              To provide search and Q&A across your own data — never another
              customer's.
            </li>
          </ul>
        </Section>

        <Section title="5. Sub-processors">
          <ul>
            <li>Supabase (Postgres + Storage)</li>
            <li>Render (API hosting)</li>
            <li>Vercel (frontend hosting)</li>
            <li>Upstash (Redis + QStash)</li>
            <li>Groq (Whisper transcription)</li>
            <li>Resend (transactional email)</li>
            <li>Sentry (error tracking)</li>
          </ul>
          <p>
            A current list with regions and contact details is at{" "}
            <a className="text-slate-900 underline" href="/subprocessors">
              /subprocessors
            </a>
            .
          </p>
        </Section>

        <Section title="6. Retention">
          Default retention is 365 days from meeting creation. Organisations
          on the Team plan can configure retention per workspace, including
          legal holds. Audio is deleted within 30 days of account
          cancellation; transcripts and summaries can be exported on request.
        </Section>

        <Section title="7. Your rights">
          You can export, correct, or delete your data at any time from
          Settings → Compliance, or by emailing us. EU residents have all
          rights under GDPR; California residents have all rights under
          CCPA/CPRA.
        </Section>

        <Section title="8. Contact">
          Privacy questions: privacy@vaktram.com. Security disclosures:
          security@vaktram.com.
        </Section>
      </article>
    </main>
  );
}

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section className="mt-10">
      <h2 className="text-xl font-semibold tracking-tight text-slate-900">
        {title}
      </h2>
      <div className="mt-3 space-y-3 text-[15px] leading-relaxed text-slate-700 [&_a]:text-slate-900 [&_li]:my-1 [&_ul]:ml-5 [&_ul]:list-disc">
        {children}
      </div>
    </section>
  );
}
